"""
This module contains base classes for dictionaries.
"""

import abc
from typing import Optional, Protocol, Union

from ekonlpy.utils.io import installpath

LEXICON_PATH = f"{installpath}/data/lexicon"


class SupportsTokenize(Protocol):
    """Structural type for tokenizer objects accepted by ``BaseDict``."""

    def tokenize(self, text: str) -> list[str]: ...


class SupportsPhraseTokenize(SupportsTokenize, Protocol):
    """A tokenizer that can also render an n-gram token as a phrase."""

    def get_phrase(self, ngram_tokens: str) -> str: ...


class BaseDict(abc.ABC):
    """
    A base class for sentiment analysis.
    For now, only 'positive' and 'negative' analysis is supported.

    Subclasses should implement ``init_dict``,
    in which ``_posset`` and ``_negset`` are initialized.

    ``Polarity`` and ``Subjectivity`` are calculated in the same way of Lydia system.
    See also http://www.cs.sunysb.edu/~skiena/lydia/

    The formula for ``Polarity`` is,

    .. math::

        Polarity= \\frac{N_{pos}-N_{neg}}{N_{pos}+N_{neg}}

    The formula for ``Subjectivity`` is,

    .. math::

        Subjectivity= \\frac{N_{pos}+N_{neg}}{N}

    :type tokenizer: obj
    :param tokenizer: An object which provides interface of ``tokenize``.
        If it is ``None``, a default tokenizer, which is defined in ``utils``, will be assigned.
    :param kind: A parameter to select a lexicon file for MPKO subclass.

        0: a lexicon file generated using Naive-bayes classifier with 5-gram tokens as features and
            changes of call rates as positive/negative label.

        1: a lexicon file generated by polarity induction and seed propagation method with 5-gram tokens.

        2: a lexicon file to measure uncertainty, which is generated by seed propagation method.

    """

    TAG_POL = "Polarity"
    TAG_SUB = "Subjectivity"
    TAG_POS = "Positive"
    TAG_NEG = "Negative"

    EPSILON = 1e-6

    def __init__(
        self,
        tokenizer: Optional[SupportsTokenize] = None,
        kind: Optional[int] = None,
        intensity_cutoff: Optional[float] = None,
    ):
        self._posdict: dict[str, int] = {}
        self._negdict: dict[str, int] = {}
        self._poldict: dict[str, float] = {}
        self._intensity_cutoff: Optional[float] = intensity_cutoff
        self._tokenizer: SupportsTokenize
        self.init_dict(kind, intensity_cutoff)
        if tokenizer is None:
            self.init_tokenizer(kind)
        else:
            self._tokenizer = tokenizer

        assert self._posdict and self._negdict  # noqa: S101

    def tokenize(self, text: str) -> list[str]:
        """
        :type text: str
        :returns: list
        """
        return self._tokenizer.tokenize(text)

    # def ngramize(self, tokens):
    #     '''
    #     :type tokens: list of tokens
    #     :returns: list
    #     '''
    #     return self._tokenizer.ngramize(tokens)

    @abc.abstractmethod
    def init_tokenizer(self, kind: Optional[int]) -> None:
        pass

    @abc.abstractmethod
    def init_dict(self, kind: Optional[int], intensity_cutoff: Optional[float]) -> None:
        pass

    def _get_score(self, term: str, by_count: bool = True) -> float:
        """Get score for a single term.
        - +1 for positive terms.
        - -1 for negative terms.
        - 0 for others.

        :returns: int
        """
        if not by_count:
            return self._poldict.get(term, 0)
        if term in self._posdict:
            return self._posdict[term]
        elif term in self._negdict:
            return self._negdict[term]
        else:
            return 0

    def get_score(
        self,
        terms: Union[list[str], tuple[str, ...]],
        by_count: bool = True,
        return_breakdown: bool = False,
    ) -> dict[str, object]:
        """Get score for a list of terms.

        :type terms: list
        :param terms: A list of terms to be analyzed.
        :param by_count: if True, use number of occruences of sentiment tokens
        :param return_breakdown: if True, return detailed breakdown of each term's polarity

        :returns: dict
        """
        assert isinstance(terms, (list, tuple))  # noqa: S101
        score_li = [self._get_score(t, by_count) for t in terms]
        pos_score_li = [s for s in score_li if s > 0]
        neg_score_li = [s for s in score_li if s < 0]

        s_pos = sum(pos_score_li)
        s_neg = sum(neg_score_li)

        s_pol = (
            (s_pos + s_neg)
            * 1.0
            / (((s_pos - s_neg) if by_count else len(score_li)) + self.EPSILON)
        )
        s_sub = (
            (len(pos_score_li) + len(neg_score_li))
            * 1.0
            / (len(score_li) + self.EPSILON)
        )

        result: dict[str, object] = {
            self.TAG_POS: s_pos,
            self.TAG_NEG: s_neg,
            self.TAG_POL: s_pol,
            self.TAG_SUB: s_sub,
        }

        if return_breakdown:
            breakdown: list[dict[str, object]] = []
            for term in terms:
                score = self._get_score(term, by_count)
                polarity = self._poldict.get(term, 0) if not by_count else score
                breakdown.append(
                    {
                        "term": term,
                        "score": score,
                        "polarity": polarity,
                        "sentiment": (
                            "positive"
                            if score > 0
                            else "negative" if score < 0 else "neutral"
                        ),
                    }
                )
            result["breakdown"] = breakdown

        return result

    def get_phrase_breakdown(
        self,
        terms: Union[list[str], tuple[str, ...]],
        tokenizer: Optional[SupportsPhraseTokenize] = None,
    ) -> list[dict[str, object]]:
        """Get detailed breakdown with human-readable phrases for n-gram tokens.

        :type terms: list
        :param terms: A list of n-gram terms to be analyzed
        :param tokenizer: Tokenizer instance with get_phrase method (e.g., MPTokenizer)

        :returns: list of dicts with term, phrase, score, polarity, sentiment
        """
        breakdown: list[dict[str, object]] = []
        for term in terms:
            score = self._get_score(term, by_count=True)
            polarity = self._poldict.get(term, 0)

            # Get human-readable phrase if tokenizer supports it
            phrase = term
            if tokenizer and hasattr(tokenizer, "get_phrase"):
                try:
                    phrase = tokenizer.get_phrase(term)
                except Exception:
                    phrase = term

            breakdown.append(
                {
                    "term": term,
                    "phrase": phrase,
                    "score": score,
                    "polarity": polarity,
                    "sentiment": (
                        "positive"
                        if score > 0
                        else "negative" if score < 0 else "neutral"
                    ),
                }
            )

        return breakdown
