---
name: deploy-docs
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - "README.md"
      - "mkdocs.yaml"
      - "docs/**.md"
      - "docs/images/**"
      - ".github/workflows/deploy-docs.yaml"

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: |
          pip install -r docs/requirements.txt
          mkdocs gh-deploy --force
