---
name: lint & test

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - "*"
    paths:
      - "src/**"
      - "tests/**"

jobs:
  build:
    # Name the Job
    name: test-code-base
    # Set the agent to run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.12]

    steps:
      # Checkout the code base #
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        run: |
          set -o pipefail
          make install

      - name: Run checks
        run: |
          set -o pipefail
          make check

      - name: Run unit-tests
        run: |
          set -o pipefail
          make test

      - name: Pytest coverage GitHub summary
        run: |
          set -o pipefail
          echo '# Coverage report' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat tests/pytest-coverage.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo '\n\n\n'

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # required
          fail_ci_if_error: false # optional (default = false)
          verbose: true # optional (default = false)
