---
name: semantic-release-test

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - test-release*

concurrency:
  group: release-publication
  cancel-in-progress: false

jobs:
  validate:
    uses: ./.github/workflows/lint_and_test.yaml
    permissions:
      contents: read

  release:
    needs: validate
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      # Note: we need to checkout the repository at the workflow sha in case during the workflow
      # the branch was updated. To keep PSR working with the configured release branches,
      # we force a checkout of the desired release branch but at the workflow sha HEAD.
      - name: Setup | Checkout Repository at workflow sha
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          ref: ${{ github.sha }}

      - name: Setup | Force correct release branch on workflow sha
        env:
          RELEASE_BRANCH: ${{ github.ref_name }}
          RELEASE_SHA: ${{ github.sha }}
        run: |
          git checkout -B "$RELEASE_BRANCH" "$RELEASE_SHA"

      - name: Action | Semantic Version Release
        id: release
        # Adjust tag with desired version if applicable.
        uses: python-semantic-release/python-semantic-release@9a026e9303981c866c3425723009becb2437c757 # v10.6.2
        with:
          build: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_committer_name: "github-actions"
          git_committer_email: "actions@users.noreply.github.com"

      - name: Publish | Upload package to TestPyPI
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2
        if: steps.release.outputs.released == 'true'
        with:
            password: ${{ secrets.TEST_PYPI_API_TOKEN }}
            repository-url: https://test.pypi.org/legacy/

      - name: Publish | Upload to GitHub Release Assets
        uses: python-semantic-release/publish-action@6d89e2de8d40ecb3717316ecbbf15a6fa8ea9039 # v10.6.2
        if: steps.release.outputs.released == 'true'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.release.outputs.tag }}
